excluded:
  - Carthage
  - Pods
  - Duiet/Sources/Common/R.generated.swift

function_body_length: 80

disabled_rules:
  - identifier_name
  - force_try
  - array_init
  - closure_body_length
  - conditional_returns_on_newline
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - empty_xctest_method
  - explicit_acl
  - explicit_enum_raw_value
  - explicit_top_level_acl
  - explicit_type_interface
  - file_header
  - file_name
  - force_unwrapping
  - implicitly_unwrapped_optional
  - multiline_arguments_brackets
  - multiline_literal_brackets
  - multiline_parameters_brackets
  - no_grouping_extension
  - trailing_closure
  - type_contents_order
  - unavailable_function
  - private_outlet
  - prohibited_interface_builder
  - overridden_super_call
  - prefixed_toplevel_constant
  - required_deinit
  - strong_iboutlet
  - vertical_parameter_alignment_on_call

opt_in_rules:
  - anyobject_protocol
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - convenience_type
  - discouraged_object_literal
  - empty_string
  - explicit_init
  - explicit_self
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_types_order
  - first_where
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - missing_docs
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_parameters
  - nimble_operator
  - no_extension_access_modifier
  - nslocalizedstring_key
  - nslocalizedstring_require_bundle
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - override_in_extension
  - pattern_matching_keywords
  - private_action
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strict_fileprivate
  - switch_case_on_newline
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - unused_declaration
  - unused_import
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition
